AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mini-CSPM scheduled scanner stack

Parameters:
  DeploymentRegion:
    Type: String
    Default: us-east-1
    Description: Primary AWS region for the scheduled Lambda.
  ScheduleExpression:
    Type: String
    Default: rate(24 hours)
    Description: EventBridge schedule (rate or cron expression).
  ReportBucketName:
    Type: String
    Description: Name for the S3 bucket storing generated reports.
  ResultsTableName:
    Type: String
    Description: Name for the DynamoDB table storing execution results.
  EnablePdf:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: Toggle PDF report generation.
  EnableHtml:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: Toggle HTML report generation.
  AutoRemediateMode:
    Type: Number
    Default: 0
    AllowedValues: [0, 1, 2]
    Description: 0=disabled, 1=dry-run, 2=apply safe remediations.
  CsvPrefix:
    Type: String
    Default: reports/csv/
    Description: S3 prefix for CSV reports.
  HtmlPrefix:
    Type: String
    Default: reports/html/
    Description: S3 prefix for HTML reports.
  PdfPrefix:
    Type: String
    Default: reports/pdf/
    Description: S3 prefix for PDF reports.
  CisVersion:
    Type: String
    Default: v1_5
    AllowedValues: [v1_5, v5_0]
    Description: CIS benchmark version to execute.
  RetainDaysS3:
    Type: Number
    Default: 365
    Description: Number of days to retain S3 report objects.
  RetainDaysDdb:
    Type: Number
    Default: 365
    Description: Number of days to retain DynamoDB execution rows.
  RemediationApplyParameter:
    Type: String
    Default: mini-cspm/remediation-apply
    Description: SSM parameter name whose value must be true to enable APPLY mode.

Globals:
  Function:
    Runtime: python3.11
    Timeout: 900
    MemorySize: 512
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref ResultsTableName
        REPORT_BUCKET: !Ref ReportBucketName
        ENABLE_PDF: !Ref EnablePdf
        ENABLE_HTML: !Ref EnableHtml
        AUTO_REMEDIATE: !Ref AutoRemediateMode
        CSV_PREFIX: !Ref CsvPrefix
        HTML_PREFIX: !Ref HtmlPrefix
        PDF_PREFIX: !Ref PdfPrefix
        AUTO_REMEDIATE_APPLY: 'false'
        REMEDIATION_APPLY_PARAMETER: !Ref RemediationApplyParameter
        CIS_VERSION: !Ref CisVersion
        RETAIN_DAYS_S3: !Ref RetainDaysS3
        RETAIN_DAYS_DDB: !Ref RetainDaysDdb
    Policies:
      - AWSLambdaBasicExecutionRole

Resources:
  ResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ResultsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  ReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ReportBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: retain-mini-cspm
            Status: Enabled
            ExpirationInDays: !Ref RetainDaysS3
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 90

  MiniCSPMFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mini-cspm-function
      Handler: src/handler.lambda_handler
      CodeUri: src/
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: IAMRead
              Effect: Allow
              Action:
                - iam:GetAccountSummary
                - iam:ListUsers
                - iam:ListMFADevices
                - iam:GetAccountPasswordPolicy
                - iam:ListAttachedUserPolicies
                - iam:ListVirtualMFADevices
              Resource: '*'
            - Sid: CloudTrailReadUpdate
              Effect: Allow
              Action:
                - cloudtrail:DescribeTrails
                - cloudtrail:GetTrailStatus
                - cloudtrail:GetEventSelectors
                - cloudtrail:UpdateTrail
              Resource: !Sub arn:${AWS::Partition}:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/*
            - Sid: LogsAndAlarms
              Effect: Allow
              Action:
                - logs:DescribeMetricFilters
                - logs:PutMetricFilter
                - cloudwatch:PutMetricAlarm
              Resource: '*'
            - Sid: Ec2SecurityGroups
              Effect: Allow
              Action:
                - ec2:DescribeSecurityGroups
                - ec2:RevokeSecurityGroupIngress
              Resource: '*'
            - Sid: S3AccountControls
              Effect: Allow
              Action:
                - s3control:GetPublicAccessBlock
                - s3control:PutPublicAccessBlock
              Resource: '*'
            - Sid: S3ReportWrites
              Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub arn:${AWS::Partition}:s3:::${ReportBucketName}/*
            - Sid: DynamoPersistence
              Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:Query
                - dynamodb:GetItem
              Resource: !GetAtt ResultsTable.Arn
            - Sid: StsIdentity
              Effect: Allow
              Action:
                - sts:GetCallerIdentity
              Resource: '*'
            - Sid: SsmParameterRead
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${RemediationApplyParameter}
      Events:
        ScheduledRun:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Name: mini-cspm-schedule
            Description: Trigger Mini-CSPM evaluations on a cadence.
            Enabled: true

  MiniCSPMPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MiniCSPMFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MiniCSPMFunction.ScheduledRun.Arn

Outputs:
  TableName:
    Description: DynamoDB table storing Mini-CSPM execution results.
    Value: !Ref ResultsTableName
  ReportBucketName:
    Description: S3 bucket containing generated reports.
    Value: !Ref ReportBucketName
  FunctionArn:
    Description: Deployed Lambda function ARN.
    Value: !GetAtt MiniCSPMFunction.Arn
  ScheduleArn:
    Description: EventBridge rule triggering the scanner.
    Value: !GetAtt MiniCSPMFunction.ScheduledRun.Arn
