"""Package containing individual AWS CIS checks and registry."""

from __future__ import annotations

from typing import Dict

from . import (
    cis_1_1_root_mfa,
    cis_1_2_no_root_keys,
    cis_1_5_password_policy,
    cis_1_22_mfa_console_users,
    cis_2_1_cloudtrail_all_regions,
    cis_2_2_cloudtrail_log_validation,
    cis_2_3_cloudtrail_encrypted_kms,
    cis_3_1_unauth_api_metric_filter,
    cis_4_1_sg_no_0_0_0_0_22_3389,
    cis_5_1_s3_account_pab_on,
    cis_1_3_root_access_key_rotated,
    cis_1_4_unused_credentials_disabled,
    cis_1_6_immediate_password_policy,
    cis_1_7_root_hardware_mfa,
    cis_1_8_vpc_flow_logs,
    cis_1_9_password_policy_expiry,
    cis_1_10_no_inline_policies_root,
    cis_1_11_no_admin_privilege_escalation,
    cis_1_12_awsmfa_console,
    cis_1_13_credential_report,
    cis_1_14_iam_access_analyzer,
    cis_1_15_no_root_access_keys,
    cis_1_16_securityhub_enabled,
    cis_1_17_waf_enabled,
    cis_1_18_guardduty_enabled,
    cis_1_19_cloudtrail_enabled,
    cis_1_20_iam_user_rotation,
    cis_1_21_kms_rotations,
    cis_2_4_cloudtrail_bucket_logging,
    cis_2_5_s3_bucket_encryption,
    cis_3_2_cloudwatch_alarm_root,
)  # noqa: E402

CHECK_REGISTRY: Dict[str, callable] = {
    "CIS-1.1": cis_1_1_root_mfa.run,
    "CIS-1.2": cis_1_2_no_root_keys.run,
    "CIS-1.3": cis_1_3_root_access_key_rotated.run,
    "CIS-1.4": cis_1_4_unused_credentials_disabled.run,
    "CIS-1.5": cis_1_5_password_policy.run,
    "CIS-1.6": cis_1_6_immediate_password_policy.run,
    "CIS-1.7": cis_1_7_root_hardware_mfa.run,
    "CIS-1.8": cis_1_8_vpc_flow_logs.run,
    "CIS-1.9": cis_1_9_password_policy_expiry.run,
    "CIS-1.10": cis_1_10_no_inline_policies_root.run,
    "CIS-1.11": cis_1_11_no_admin_privilege_escalation.run,
    "CIS-1.12": cis_1_12_awsmfa_console.run,
    "CIS-1.13": cis_1_13_credential_report.run,
    "CIS-1.14": cis_1_14_iam_access_analyzer.run,
    "CIS-1.15": cis_1_15_no_root_access_keys.run,
    "CIS-1.16": cis_1_16_securityhub_enabled.run,
    "CIS-1.17": cis_1_17_waf_enabled.run,
    "CIS-1.18": cis_1_18_guardduty_enabled.run,
    "CIS-1.19": cis_1_19_cloudtrail_enabled.run,
    "CIS-1.20": cis_1_20_iam_user_rotation.run,
    "CIS-1.21": cis_1_21_kms_rotations.run,
    "CIS-1.22": cis_1_22_mfa_console_users.run,
    "CIS-2.1": cis_2_1_cloudtrail_all_regions.run,
    "CIS-2.2": cis_2_2_cloudtrail_log_validation.run,
    "CIS-2.3": cis_2_3_cloudtrail_encrypted_kms.run,
    "CIS-2.4": cis_2_4_cloudtrail_bucket_logging.run,
    "CIS-2.5": cis_2_5_s3_bucket_encryption.run,
    "CIS-3.1": cis_3_1_unauth_api_metric_filter.run,
    "CIS-3.2": cis_3_2_cloudwatch_alarm_root.run,
    "CIS-4.1": cis_4_1_sg_no_0_0_0_0_22_3389.run,
    "CIS-5.1": cis_5_1_s3_account_pab_on.run,
}

__all__ = sorted(CHECK_REGISTRY.keys())
