name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: pip-audit security scan
        run: pip-audit --fail-on vulnerability --severity HIGH

      - name: Run tests with coverage
        run: pytest --cov=infra/sam-app/src --cov-report=term-missing --cov-fail-under=80

      - name: Generate sample CSV
        run: python scripts/generate_sample_csv.py

      - name: Upload sample artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-out
          path: sample_out.csv
